spring:
  data:
    cassandra:
      contact-points: 192.168.31.29
      port: 9042
      keyspace-name: kairosdb
      username: cassandra
      password: cassandra
      compression: lz4
      local-datacenter: kairosdb
      session-name: KairosdbQuery
  kafka:
    bootstrap-servers: 192.168.31.29:9097
    listener:
      type: batch
      concurrency: 10
      log-container-config: true
      client-id: kairos-app-
    consumer:
      group-id: dn
      enable-auto-commit: true
      client-id: kairos-app
      max-poll-records: 10
      auto-offset-reset: latest
  datasource:
    url: jdbc:p6spy:postgresql://192.168.31.29:44322/ry-vue
    username: inori
    password: inori0114
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    #type: org.postgresql.jdbc2.optional.PoolingDataSource
    name: DnAdminDatabase
    generate-unique-name: false
    hikari:
      register-mbeans: true
      auto-commit: true
      connection-test-query: select version();
      idle-timeout: 20000
      minimum-idle: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      schema: public



api:
  swagger:
    enable: true
    type: oas_30

kairos:
  domain: 192.168.31.29
  port: 8880