server:
  port: 29550

spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  application:
    name: KairosdbServer
  security:
    user:
      name: admin
      password: admin123
      roles: admin
  jmx:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  data:
    jpa:
      repositories:
        bootstrap-mode: default

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
    migrate-legacy-ids: true